apiVersion: v1
kind: ConfigMap
metadata:
    name: my-map
data:
  school: 'LOL'
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - env
    imagePullPolicy: IfNotPresent
    env:
      - name: WHAT_SCHOOL
        valueFrom:
          configMapKeyRef:
            name: my-map
            key: school
      - name: STUDENT_NAME
        value: "Artem Kajalainen"
      - name: SCHOOL
        value: "Linux Academy"
      - name: KUBERNETES
        value: "\"is awesome\""
  restartPolicy: Always